// Generated by CoffeeScript 1.9.1
(function() {
  var config;

  config = {
    consumer_key: '',
    consumer_secret: '',
    access_token_key: '',
    access_token_secret: ''
  };

  module.exports = config;

}).call(this);
